export const elements: Record<string, { name: string; type: string }> = {
  FUNGUS: { name: '01.Rojo-Hongos.png', type: 'EXTRES' },
  FUNGICIDE: { name: '01.Verde-Antifungicos.png', type: 'TREATMENT' },
  MINERAL_DEFICIENCIES: { name: '02.Rojo-DefMInerales.png', type: 'EXTRES' },
  FERTILIZER: { name: '02.Verde-Fertilizantes.png', type: 'TREATMENT' },
  WEED: { name: '03.Rojo-MalasHierbas.png', type: 'EXTRES' },
  HERBICIDE: { name: '03.Verde-Herbicida.png', type: 'TREATMENT' },
  DEFOLIATORS_BUGS: { name: '04.Rojo-InsectosDevora.png', type: 'EXTRES' },
  DROGHT: { name: '04.Rojo-Sequia.png', type: 'EXTRES' },
  INSECTICIDE: { name: '04.Verde-Insecticida.png', type: 'TREATMENT' },
  APHIDS_BUGS: { name: '05.Rojo-Afidos.png', type: 'EXTRES' },
  INSECTICIDE2: { name: '05.Verde-Insecticida_copia.png', type: 'TREATMENT' },
  NEMATODE: { name: '06.Rojo-Nematodos.png', type: 'EXTRES' },
  NEMATICIDE: { name: '06.Verde-Nematicidas.png', type: 'TREATMENT' },
  WATER: { name: '07.Verde-lluvia.png', type: 'TREATMENT' },
  PHOTOPERIOD: { name: 'DiaNeutro.png', type: 'INDUCTING_CONDITION' },
  FLOWER: { name: 'Flores1.png', type: 'FLOWER' },
  FLOWER2: { name: 'Flores2.png', type: 'FLOWER' },
  COLD: { name: 'Frio.png', type: 'INDUCTING_CONDITION' },
  FRUIT: { name: 'Frutos1.png', type: 'FRUIT' },
  FRUIT2: { name: 'Frutos2.png', type: 'FRUIT' },
  LEAVE: { name: 'hojas.png', type: 'VEGETETIVE_ORGAN' },
  ROOT: { name: 'raiz.png', type: 'VEGETETIVE_ORGAN' },
  STEM: { name: 'tallo.png', type: 'VEGETETIVE_ORGAN' }
}
